### ISSUE TITLE
Read of closed file when a test fails and Report Portal is active

### ISSUE THREAD

**Issue by rafutek** [ElSnoMan/pyleniumio#157]
I am trying Pylenium with pytest-bdd and Report Portal, it's really nice.

However, when I launch a test that fails with `pytest --reportportal` I have this error:

> Traceback (most recent call last):
  File "PROJECT/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "PROJECT/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "PROJECT/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "PROJECT/venv/lib/python3.9/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "PROJECT/venv/lib/python3.9/site-packages/_pytest/main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "PROJECT/venv/lib/python3.9/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "PROJECT/venv/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "PROJECT/venv/lib/python3.9/site-packages/pytest_reportportal/plugin.py", line 149, in pytest_sessionfinish
    session.config.py_test_service.finish_launch()
  File "PROJECT/venv/lib/python3.9/site-packages/pytest_reportportal/service.py", line 403, in finish_launch
    self.rp.finish_launch(**fl_rq)
  File "PROJECT/venv/lib/python3.9/site-packages/reportportal_client/service.py", line 249, in finish_launch
    self.log_batch([], force=True)
  File "PROJECT/venv/lib/python3.9/site-packages/reportportal_client/service.py", line 526, in log_batch
    r = self.session.post(
  File "PROJECT/venv/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "PROJECT/venv/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "PROJECT/venv/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "PROJECT/venv/lib/python3.9/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "PROJECT/venv/lib/python3.9/site-packages/requests/models.py", line 507, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "PROJECT/venv/lib/python3.9/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
ValueError: read of closed file

And the test still runs in Report Portal.

Do you have any idea on how to solve this ?

Thanks 😁

**Comment by ElSnoMan** [comment]
@rafutek This looks like a problem with Report Portal (RP). I haven't tried using `pytest-bdd` with RP yet, but this wouldn't be a Pylenium issue.

Sorry, I know that's not a very helpful answer, but I'd post the issue on their Slack or repo :(

**Comment by rafutek** [comment]
@ElSnoMan No problem, now I know it's not a Pylenium issue ;) Thanks !
