### ISSUE TITLE
pylenium --version raises Exception

### ISSUE THREAD

**Issue by rnestler** [ElSnoMan/pyleniumio#246]
When I try to execute `pylenium --version` it will raise an Exception:
```
pylenium --version
Traceback (most recent call last):
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/bin/pylenium", line 8, in <module>
    sys.exit(cli())
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/home/raphael/.cache/pypoetry/virtualenvs/qualib-ZPYchWbI-py3.9/lib/python3.9/site-packages/click/decorators.py", line 441, in callback
    raise RuntimeError(
RuntimeError: 'pylenium' is not installed. Try passing 'package_name' instead.
```

I guess the issue is that the executable is named `pylenium`, but the Python distribution package is called pyleniumio.

**Comment by rnestler** [comment]
> Does it work with this command?

Sadly no: `command not found: pyleniumio`

Maybe the `click` version is related? I have `click 8.1.2` in my poetry env.

**Comment by ElSnoMan** [comment]
Ah, could be! I had `click 7.1.2` but I'll test with `8.1.2` and see what I can find. Hopefully that's the issue so I can solve it by pinning a working version 😄

**Comment by ElSnoMan** [comment]
That was it! I got the exact same error you got when I updated click to `8.1.2` and fixed the error once I downgraded to `7.1.2` again. I will update this 💪🏽 

```bash
# FROM
click>=7.1.2

# TO
click=7.1.2
```

**Comment by rnestler** [comment]
> Hopefully that's the issue so I can solve it by pinning a working version

It seems like click is using semantic versioning, so anything `>=7.1.2` but `<8.0.0` should work?

**Comment by ElSnoMan** [comment]
Click was pinned to `"click>=7.1.2, <8.0.0"` in Pylenium release `v1.15.3`
